if (!window.ActiveXObject){ document.write("<div class=\"mam_async_17612_2\" style=\"text-align: center; margin: 0px auto; width:728px; height:90px; position:relative;\">");document.write("<style type=\"text\/css\"> .madLink{ position:absolute; bottom:0px; left:0px; width:14px; height:14px; min-width:14px; max-width:14px; min-height:14px; max-height:14px; color:#FFF; background-color:#FF0000; text-align:center; font:11px Arial, Tahoma, sans-serif; font-weight:bold; opacity:0.6; filter:alpha(opacity=60); } DIV.madLink:hover { cursor:pointer; color:#99ffff; opacity:.9; filter:alpha(opacity=90); } <\/style>"); }var prot = 'http:'; var patternUrl = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;  var psa = 0; var resultApproved = null; var resultServing = null; var approvedURLs = ['fakemailgenerator.com']; var adServingURLs = [];  var store = ""; var resultBlocked = null; var blockedURLs = ["porn","topless","fuck","xxx","tits","pussy","xrated","cunt","gangbang","blowjob","jailbait","nsfw","murder","suicide","violence","abused","rape","sex","nipple","porno","carajo","tetas","co&ntilde;o","orgia","mamada","muertos","disparo","muertos","muerto","asesinato","suicidio","violencia","abusado","violaci&oacute;n","sexo","pez&oacute;n","sesso"]; var googlePage = 'www.fakemailgenerator.com'; var SiteID='17612';  var realURL = 1; var iframe = 0; var url = 0; var src = 0;  if (top === self){ var refURL = document.location.href; url = encodeURIComponent(document.location.href); src = 0; } else { var refURL = document.referrer; url = encodeURIComponent(document.location.href); src = encodeURIComponent(document.referrer); } if(typeof setMIframe !== 'undefined'){ iframe = setMIframe; } if(typeof setMRefURL !== 'undefined'){ refURL = setMRefURL; if(iframe == 1){ src = setMRefURL; }else{ url = setMRefURL; } }  if(!refURL){ refURL = googlePage ? prot+'//'+googlePage : document.location.href; realURL = 0; }  if(iframe == 1 && !src){ refURL = document.location.href; src = 'BlankRefServe'; realURL = 0; }  var pb728x90='46194/17612/default/728x90.js';  if(patternUrl.test(refURL.toLowerCase())){ for(var i = 0; i < blockedURLs.length; i++){ if(refURL.toLowerCase().match(blockedURLs[i].toLowerCase())){ resultBlocked = true; break; }} if(!resultBlocked){ for(var i = 0; i < approvedURLs.length; i++){ if(refURL.toLowerCase().match(approvedURLs[i].toLowerCase())) { resultApproved = true; break; }} for(var i = 0; i < adServingURLs.length; i++){ if(refURL.toLowerCase().match(adServingURLs[i].toLowerCase())){ resultServing = adServingURLs[i]; break; }}  if(resultApproved || resultServing){ var tt = '_' + Math.floor((Math.random() * 10000000) + 1);  document.write("<img src='//pixel.madadsmedia.com/?site=17612&pub=46194&size=20&iframe="+iframe+"&url="+url+"&src="+src+"&store="+store+"' style='display:none'>");var divn = Math.floor((Math.random() * 10000000) + 1);
                document.write("<div id=\""+ divn +"\"></div>");
                var adIframe = document.createElement('iframe');
                adIframe.id = '728x90' + tt; adIframe.width = '728'; adIframe.height = '90'; adIframe.scrolling = 'no'; adIframe.frameBorder = 0; adIframe.marginHeight = 0; adIframe.marginWidth = 0;
                adIframe.sandbox= 'allow-same-origin allow-scripts allow-forms allow-popups';
                adIframe.src = 'about:blank'; 
                document.getElementById(""+ divn +"").appendChild(adIframe);
                var JS = "<div id='madcid' tt='" + tt + "'></div>" + "<scr" + "ipt type='text/javascript' src='//ads-by.madadsmedia.com/tags/46194/17612/bidder/728x90.js'></scr" + "ipt>";
                var myContent = '<!DOCTYPE html>' + '<html><head><title>MadAdsMedia.com Advertisements</title></head><body>' + JS + '</body></html>';
                adIframe.contentWindow.document.open('text/html', 'replace');
                adIframe.contentWindow.document.write(myContent);
                adIframe.contentWindow.document.close();} else { psa = '1'; var dw = document; if(typeof pb728x90 != 'undefined'){ dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="//ads-by.madadsmedia.com/tags/' + pb728x90 + '">'); dw.write('<\/scr' + 'ipt>'); } else { dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="//ads-by.madadsmedia.com/tags/46194/17612/default/728x90.js">'); dw.write('<\/scr' + 'ipt>'); } }} else { document.write('<img src="'+prot+'\//pixel.madadsmedia.com/?site=17612&pub=46194&size=20&iframe='+iframe+'&url='+url+'&src='+src+'&blocked=1" style="display:none">');  var nonPixel = 1; var dw = document; if(typeof pb728x90 != 'undefined'){ dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="//ads-by.madadsmedia.com/tags/' + pb728x90 + '">'); dw.write('<\/scr' + 'ipt>'); } else { dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="//ads-by.madadsmedia.com/tags/46194/17612/default/728x90.js">'); dw.write('<\/scr' + 'ipt>'); } }} if (!window.ActiveXObject){ document.write("<div class=\"madLink\"><span><a style=\"color: white; text-decoration: none\" href=\""+prot+"//www.madadsmedia.com\/landing\/1\/ref\/30\/\" target=\"_blank\">?</a></span></div>"); document.write("<\/div>"); }